### ISSUE TITLE
Files aren't displayed

### ISSUE THREAD

**Issue by bombei** [prototype95711/cscart-development-helper-vscode#2]
Hi!
First of all congratulations for this Addon it's super.

I've installed it but when I choose a addon (the list is correct) the explorer shows the folder but doesn't show anything inside it.

What can be the issue? should I change something?

Thanks
Miguel Teixeira

**Comment by prototype95711** [comment]
Hi! 

I wonder what it looks like. I have not encountered such a bug.

Can you provide a screenshot of the error? I am interested in the experience of using the plugin in different cases. 
Thank you.

Gleb Perfiliev

**Comment by bombei** [comment]
Hi!
Sure
![image](https://github.com/prototype95711/cscart-development-helper-vscode/assets/2701703/f000641a-6cc3-4654-b7e1-19cde8ccc836)

But the addon folders have files inside:
![image](https://github.com/prototype95711/cscart-development-helper-vscode/assets/2701703/ae013000-e0f4-45f9-a3c1-300c089018bd)

But when i click on "Open Addon" all of my addons apeear in the list, but when i choose one of them, all came empty.

Also the overrides in the terminal it's not working:
![image](https://github.com/prototype95711/cscart-development-helper-vscode/assets/2701703/17e58f6f-4fa6-4ca9-be5b-b1ac255c7ee2)

I hope to be helpful....
If you need some more tests tell me please.
Thanks in advance
Miguel

**Comment by prototype95711** [comment]
I haven't seen exactly this problem. But this problem could have been fixed in one of the previous plugin updates, since I was fixing a similar problem.

If you are still encountering it, you can provide your airship add-on files (if possible for you) so that I can resolve it.

**Comment by prototype95711** [comment]
Issue closed due to lack of activity
